apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate-acme
spec:
  secretName: certificate-and-key-secret
  duration: 24h
  renewBefore: 12h
  dnsNames:
  - app1.com
  - app2.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - foo.example.com
      - bar.example.com
  issuerRef:
    name: issuer-name
    kind: Issuer
